<?php
/**
 * Receipt
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Receipt Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Receipt implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Receipt';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'receipt_number' => 'string',
        'sales_date_time' => 'float',
        'sales_customer_type' => 'string',
        'patient_license_number' => 'string',
        'caregiver_license_number' => 'string',
        'identification_method' => 'string',
        'total_packages' => 'int',
        'total_price' => 'float',
        'transactions' => '\Swagger\Client\Model\Transaction[]',
        'is_final' => 'bool',
        'archived_date' => 'string',
        'last_modified' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'receipt_number' => null,
        'sales_date_time' => null,
        'sales_customer_type' => null,
        'patient_license_number' => null,
        'caregiver_license_number' => null,
        'identification_method' => null,
        'total_packages' => null,
        'total_price' => null,
        'transactions' => null,
        'is_final' => null,
        'archived_date' => null,
        'last_modified' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'Id',
        'receipt_number' => 'ReceiptNumber',
        'sales_date_time' => 'SalesDateTime',
        'sales_customer_type' => 'SalesCustomerType',
        'patient_license_number' => 'PatientLicenseNumber',
        'caregiver_license_number' => 'CaregiverLicenseNumber',
        'identification_method' => 'IdentificationMethod',
        'total_packages' => 'TotalPackages',
        'total_price' => 'TotalPrice',
        'transactions' => 'Transactions',
        'is_final' => 'IsFinal',
        'archived_date' => 'ArchivedDate',
        'last_modified' => 'LastModified'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'receipt_number' => 'setReceiptNumber',
        'sales_date_time' => 'setSalesDateTime',
        'sales_customer_type' => 'setSalesCustomerType',
        'patient_license_number' => 'setPatientLicenseNumber',
        'caregiver_license_number' => 'setCaregiverLicenseNumber',
        'identification_method' => 'setIdentificationMethod',
        'total_packages' => 'setTotalPackages',
        'total_price' => 'setTotalPrice',
        'transactions' => 'setTransactions',
        'is_final' => 'setIsFinal',
        'archived_date' => 'setArchivedDate',
        'last_modified' => 'setLastModified'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'receipt_number' => 'getReceiptNumber',
        'sales_date_time' => 'getSalesDateTime',
        'sales_customer_type' => 'getSalesCustomerType',
        'patient_license_number' => 'getPatientLicenseNumber',
        'caregiver_license_number' => 'getCaregiverLicenseNumber',
        'identification_method' => 'getIdentificationMethod',
        'total_packages' => 'getTotalPackages',
        'total_price' => 'getTotalPrice',
        'transactions' => 'getTransactions',
        'is_final' => 'getIsFinal',
        'archived_date' => 'getArchivedDate',
        'last_modified' => 'getLastModified'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['receipt_number'] = isset($data['receipt_number']) ? $data['receipt_number'] : null;
        $this->container['sales_date_time'] = isset($data['sales_date_time']) ? $data['sales_date_time'] : null;
        $this->container['sales_customer_type'] = isset($data['sales_customer_type']) ? $data['sales_customer_type'] : null;
        $this->container['patient_license_number'] = isset($data['patient_license_number']) ? $data['patient_license_number'] : null;
        $this->container['caregiver_license_number'] = isset($data['caregiver_license_number']) ? $data['caregiver_license_number'] : null;
        $this->container['identification_method'] = isset($data['identification_method']) ? $data['identification_method'] : null;
        $this->container['total_packages'] = isset($data['total_packages']) ? $data['total_packages'] : null;
        $this->container['total_price'] = isset($data['total_price']) ? $data['total_price'] : null;
        $this->container['transactions'] = isset($data['transactions']) ? $data['transactions'] : null;
        $this->container['is_final'] = isset($data['is_final']) ? $data['is_final'] : null;
        $this->container['archived_date'] = isset($data['archived_date']) ? $data['archived_date'] : null;
        $this->container['last_modified'] = isset($data['last_modified']) ? $data['last_modified'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets receipt_number
     *
     * @return string
     */
    public function getReceiptNumber()
    {
        return $this->container['receipt_number'];
    }

    /**
     * Sets receipt_number
     *
     * @param string $receipt_number receipt_number
     *
     * @return $this
     */
    public function setReceiptNumber($receipt_number)
    {
        $this->container['receipt_number'] = $receipt_number;

        return $this;
    }

    /**
     * Gets sales_date_time
     *
     * @return float
     */
    public function getSalesDateTime()
    {
        return $this->container['sales_date_time'];
    }

    /**
     * Sets sales_date_time
     *
     * @param float $sales_date_time sales_date_time
     *
     * @return $this
     */
    public function setSalesDateTime($sales_date_time)
    {
        $this->container['sales_date_time'] = $sales_date_time;

        return $this;
    }

    /**
     * Gets sales_customer_type
     *
     * @return string
     */
    public function getSalesCustomerType()
    {
        return $this->container['sales_customer_type'];
    }

    /**
     * Sets sales_customer_type
     *
     * @param string $sales_customer_type sales_customer_type
     *
     * @return $this
     */
    public function setSalesCustomerType($sales_customer_type)
    {
        $this->container['sales_customer_type'] = $sales_customer_type;

        return $this;
    }

    /**
     * Gets patient_license_number
     *
     * @return string
     */
    public function getPatientLicenseNumber()
    {
        return $this->container['patient_license_number'];
    }

    /**
     * Sets patient_license_number
     *
     * @param string $patient_license_number patient_license_number
     *
     * @return $this
     */
    public function setPatientLicenseNumber($patient_license_number)
    {
        $this->container['patient_license_number'] = $patient_license_number;

        return $this;
    }

    /**
     * Gets caregiver_license_number
     *
     * @return string
     */
    public function getCaregiverLicenseNumber()
    {
        return $this->container['caregiver_license_number'];
    }

    /**
     * Sets caregiver_license_number
     *
     * @param string $caregiver_license_number caregiver_license_number
     *
     * @return $this
     */
    public function setCaregiverLicenseNumber($caregiver_license_number)
    {
        $this->container['caregiver_license_number'] = $caregiver_license_number;

        return $this;
    }

    /**
     * Gets identification_method
     *
     * @return string
     */
    public function getIdentificationMethod()
    {
        return $this->container['identification_method'];
    }

    /**
     * Sets identification_method
     *
     * @param string $identification_method identification_method
     *
     * @return $this
     */
    public function setIdentificationMethod($identification_method)
    {
        $this->container['identification_method'] = $identification_method;

        return $this;
    }

    /**
     * Gets total_packages
     *
     * @return int
     */
    public function getTotalPackages()
    {
        return $this->container['total_packages'];
    }

    /**
     * Sets total_packages
     *
     * @param int $total_packages total_packages
     *
     * @return $this
     */
    public function setTotalPackages($total_packages)
    {
        $this->container['total_packages'] = $total_packages;

        return $this;
    }

    /**
     * Gets total_price
     *
     * @return float
     */
    public function getTotalPrice()
    {
        return $this->container['total_price'];
    }

    /**
     * Sets total_price
     *
     * @param float $total_price total_price
     *
     * @return $this
     */
    public function setTotalPrice($total_price)
    {
        $this->container['total_price'] = $total_price;

        return $this;
    }

    /**
     * Gets transactions
     *
     * @return \Swagger\Client\Model\Transaction[]
     */
    public function getTransactions()
    {
        return $this->container['transactions'];
    }

    /**
     * Sets transactions
     *
     * @param \Swagger\Client\Model\Transaction[] $transactions transactions
     *
     * @return $this
     */
    public function setTransactions($transactions)
    {
        $this->container['transactions'] = $transactions;

        return $this;
    }

    /**
     * Gets is_final
     *
     * @return bool
     */
    public function getIsFinal()
    {
        return $this->container['is_final'];
    }

    /**
     * Sets is_final
     *
     * @param bool $is_final is_final
     *
     * @return $this
     */
    public function setIsFinal($is_final)
    {
        $this->container['is_final'] = $is_final;

        return $this;
    }

    /**
     * Gets archived_date
     *
     * @return string
     */
    public function getArchivedDate()
    {
        return $this->container['archived_date'];
    }

    /**
     * Sets archived_date
     *
     * @param string $archived_date archived_date
     *
     * @return $this
     */
    public function setArchivedDate($archived_date)
    {
        $this->container['archived_date'] = $archived_date;

        return $this;
    }

    /**
     * Gets last_modified
     *
     * @return string
     */
    public function getLastModified()
    {
        return $this->container['last_modified'];
    }

    /**
     * Sets last_modified
     *
     * @param string $last_modified last_modified
     *
     * @return $this
     */
    public function setLastModified($last_modified)
    {
        $this->container['last_modified'] = $last_modified;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


