<?php
/**
 * CreatePlantingPlants
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CreatePlantingPlants Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CreatePlantingPlants implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreatePlantingPlants';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'plant_label' => 'string',
'plant_batch_name' => 'string',
'plant_batch_type' => 'string',
'plant_count' => 'int',
'room_name' => 'string',
'strain_name' => 'string',
'patient_license_number' => 'string',
'actual_date' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'plant_label' => null,
'plant_batch_name' => null,
'plant_batch_type' => null,
'plant_count' => null,
'room_name' => null,
'strain_name' => null,
'patient_license_number' => null,
'actual_date' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'plant_label' => 'PlantLabel',
'plant_batch_name' => 'PlantBatchName',
'plant_batch_type' => 'PlantBatchType',
'plant_count' => 'PlantCount',
'room_name' => 'RoomName',
'strain_name' => 'StrainName',
'patient_license_number' => 'PatientLicenseNumber',
'actual_date' => 'ActualDate'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'plant_label' => 'setPlantLabel',
'plant_batch_name' => 'setPlantBatchName',
'plant_batch_type' => 'setPlantBatchType',
'plant_count' => 'setPlantCount',
'room_name' => 'setRoomName',
'strain_name' => 'setStrainName',
'patient_license_number' => 'setPatientLicenseNumber',
'actual_date' => 'setActualDate'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'plant_label' => 'getPlantLabel',
'plant_batch_name' => 'getPlantBatchName',
'plant_batch_type' => 'getPlantBatchType',
'plant_count' => 'getPlantCount',
'room_name' => 'getRoomName',
'strain_name' => 'getStrainName',
'patient_license_number' => 'getPatientLicenseNumber',
'actual_date' => 'getActualDate'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['plant_label'] = isset($data['plant_label']) ? $data['plant_label'] : null;
        $this->container['plant_batch_name'] = isset($data['plant_batch_name']) ? $data['plant_batch_name'] : null;
        $this->container['plant_batch_type'] = isset($data['plant_batch_type']) ? $data['plant_batch_type'] : null;
        $this->container['plant_count'] = isset($data['plant_count']) ? $data['plant_count'] : null;
        $this->container['room_name'] = isset($data['room_name']) ? $data['room_name'] : null;
        $this->container['strain_name'] = isset($data['strain_name']) ? $data['strain_name'] : null;
        $this->container['patient_license_number'] = isset($data['patient_license_number']) ? $data['patient_license_number'] : null;
        $this->container['actual_date'] = isset($data['actual_date']) ? $data['actual_date'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets plant_label
     *
     * @return string
     */
    public function getPlantLabel()
    {
        return $this->container['plant_label'];
    }

    /**
     * Sets plant_label
     *
     * @param string $plant_label plant_label
     *
     * @return $this
     */
    public function setPlantLabel($plant_label)
    {
        $this->container['plant_label'] = $plant_label;

        return $this;
    }

    /**
     * Gets plant_batch_name
     *
     * @return string
     */
    public function getPlantBatchName()
    {
        return $this->container['plant_batch_name'];
    }

    /**
     * Sets plant_batch_name
     *
     * @param string $plant_batch_name plant_batch_name
     *
     * @return $this
     */
    public function setPlantBatchName($plant_batch_name)
    {
        $this->container['plant_batch_name'] = $plant_batch_name;

        return $this;
    }

    /**
     * Gets plant_batch_type
     *
     * @return string
     */
    public function getPlantBatchType()
    {
        return $this->container['plant_batch_type'];
    }

    /**
     * Sets plant_batch_type
     *
     * @param string $plant_batch_type plant_batch_type
     *
     * @return $this
     */
    public function setPlantBatchType($plant_batch_type)
    {
        $this->container['plant_batch_type'] = $plant_batch_type;

        return $this;
    }

    /**
     * Gets plant_count
     *
     * @return int
     */
    public function getPlantCount()
    {
        return $this->container['plant_count'];
    }

    /**
     * Sets plant_count
     *
     * @param int $plant_count plant_count
     *
     * @return $this
     */
    public function setPlantCount($plant_count)
    {
        $this->container['plant_count'] = $plant_count;

        return $this;
    }

    /**
     * Gets room_name
     *
     * @return string
     */
    public function getRoomName()
    {
        return $this->container['room_name'];
    }

    /**
     * Sets room_name
     *
     * @param string $room_name room_name
     *
     * @return $this
     */
    public function setRoomName($room_name)
    {
        $this->container['room_name'] = $room_name;

        return $this;
    }

    /**
     * Gets strain_name
     *
     * @return string
     */
    public function getStrainName()
    {
        return $this->container['strain_name'];
    }

    /**
     * Sets strain_name
     *
     * @param string $strain_name strain_name
     *
     * @return $this
     */
    public function setStrainName($strain_name)
    {
        $this->container['strain_name'] = $strain_name;

        return $this;
    }

    /**
     * Gets patient_license_number
     *
     * @return string
     */
    public function getPatientLicenseNumber()
    {
        return $this->container['patient_license_number'];
    }

    /**
     * Sets patient_license_number
     *
     * @param string $patient_license_number patient_license_number
     *
     * @return $this
     */
    public function setPatientLicenseNumber($patient_license_number)
    {
        $this->container['patient_license_number'] = $patient_license_number;

        return $this;
    }

    /**
     * Gets actual_date
     *
     * @return string
     */
    public function getActualDate()
    {
        return $this->container['actual_date'];
    }

    /**
     * Sets actual_date
     *
     * @param string $actual_date actual_date
     *
     * @return $this
     */
    public function setActualDate($actual_date)
    {
        $this->container['actual_date'] = $actual_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
