<?php
/**
 * ItemsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for itemsV1ActiveGet
     *
     * .
     *
     */
    public function testItemsV1ActiveGet()
    {
    }

    /**
     * Test case for itemsV1BrandsGet
     *
     * .
     *
     */
    public function testItemsV1BrandsGet()
    {
    }

    /**
     * Test case for itemsV1CategoriesGet
     *
     * .
     *
     */
    public function testItemsV1CategoriesGet()
    {
    }

    /**
     * Test case for itemsV1CreatePost
     *
     * .
     *
     */
    public function testItemsV1CreatePost()
    {
    }

    /**
     * Test case for itemsV1IdDelete
     *
     * .
     *
     */
    public function testItemsV1IdDelete()
    {
    }

    /**
     * Test case for itemsV1IdGet
     *
     * .
     *
     */
    public function testItemsV1IdGet()
    {
    }

    /**
     * Test case for itemsV1UpdatePost
     *
     * .
     *
     */
    public function testItemsV1UpdatePost()
    {
    }
}
