<?php
/**
 * PlantBatchesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PlantBatchesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PlantBatchesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for plantbatchesV1ActiveGet
     *
     * .
     *
     */
    public function testPlantbatchesV1ActiveGet()
    {
    }

    /**
     * Test case for plantbatchesV1AdditivesPost
     *
     * .
     *
     */
    public function testPlantbatchesV1AdditivesPost()
    {
    }

    /**
     * Test case for plantbatchesV1ChangegrowthphasePost
     *
     * .
     *
     */
    public function testPlantbatchesV1ChangegrowthphasePost()
    {
    }

    /**
     * Test case for plantbatchesV1CreatepackagesPost
     *
     * .
     *
     */
    public function testPlantbatchesV1CreatepackagesPost()
    {
    }

    /**
     * Test case for plantbatchesV1CreateplantingsPost
     *
     * .
     *
     */
    public function testPlantbatchesV1CreateplantingsPost()
    {
    }

    /**
     * Test case for plantbatchesV1DestroyPost
     *
     * .
     *
     */
    public function testPlantbatchesV1DestroyPost()
    {
    }

    /**
     * Test case for plantbatchesV1IdGet
     *
     * .
     *
     */
    public function testPlantbatchesV1IdGet()
    {
    }

    /**
     * Test case for plantbatchesV1InactiveGet
     *
     * .
     *
     */
    public function testPlantbatchesV1InactiveGet()
    {
    }

    /**
     * Test case for plantbatchesV1MoveplantbatchesPut
     *
     * .
     *
     */
    public function testPlantbatchesV1MoveplantbatchesPut()
    {
    }

    /**
     * Test case for plantbatchesV1TypesGet
     *
     * .
     *
     */
    public function testPlantbatchesV1TypesGet()
    {
    }
}
