<?php
/**
 * ManicurePlantTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ManicurePlantTest Class Doc Comment
 *
 * @category    Class
 * @description ManicurePlant
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ManicurePlantTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ManicurePlant"
     */
    public function testManicurePlant()
    {
    }

    /**
     * Test attribute "plant"
     */
    public function testPropertyPlant()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "unit_of_weight"
     */
    public function testPropertyUnitOfWeight()
    {
    }

    /**
     * Test attribute "drying_room"
     */
    public function testPropertyDryingRoom()
    {
    }

    /**
     * Test attribute "harvest_name"
     */
    public function testPropertyHarvestName()
    {
    }

    /**
     * Test attribute "patient_license_number"
     */
    public function testPropertyPatientLicenseNumber()
    {
    }

    /**
     * Test attribute "actual_date"
     */
    public function testPropertyActualDate()
    {
    }
}
