<?php
/**
 * PlantsChangeGrowthPhaseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PlantsChangeGrowthPhaseTest Class Doc Comment
 *
 * @category    Class
 * @description PlantsChangeGrowthPhase
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlantsChangeGrowthPhaseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PlantsChangeGrowthPhase"
     */
    public function testPlantsChangeGrowthPhase()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "new_tag"
     */
    public function testPropertyNewTag()
    {
    }

    /**
     * Test attribute "growth_phase"
     */
    public function testPropertyGrowthPhase()
    {
    }

    /**
     * Test attribute "new_room"
     */
    public function testPropertyNewRoom()
    {
    }

    /**
     * Test attribute "growth_date"
     */
    public function testPropertyGrowthDate()
    {
    }
}
