<?php
/**
 * PlantTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PlantTest Class Doc Comment
 *
 * @category    Class
 * @description Plant
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlantTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Plant"
     */
    public function testPlant()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "growth_phase"
     */
    public function testPropertyGrowthPhase()
    {
    }

    /**
     * Test attribute "plant_batch_id"
     */
    public function testPropertyPlantBatchId()
    {
    }

    /**
     * Test attribute "plant_batch_name"
     */
    public function testPropertyPlantBatchName()
    {
    }

    /**
     * Test attribute "plant_batch_type_name"
     */
    public function testPropertyPlantBatchTypeName()
    {
    }

    /**
     * Test attribute "strain_id"
     */
    public function testPropertyStrainId()
    {
    }

    /**
     * Test attribute "strain_name"
     */
    public function testPropertyStrainName()
    {
    }

    /**
     * Test attribute "room_id"
     */
    public function testPropertyRoomId()
    {
    }

    /**
     * Test attribute "room_name"
     */
    public function testPropertyRoomName()
    {
    }

    /**
     * Test attribute "patient_license_number"
     */
    public function testPropertyPatientLicenseNumber()
    {
    }

    /**
     * Test attribute "harvest_id"
     */
    public function testPropertyHarvestId()
    {
    }

    /**
     * Test attribute "harvested_unit_of_weight_name"
     */
    public function testPropertyHarvestedUnitOfWeightName()
    {
    }

    /**
     * Test attribute "harvested_unit_of_weight_abbreviation"
     */
    public function testPropertyHarvestedUnitOfWeightAbbreviation()
    {
    }

    /**
     * Test attribute "harvested_wet_weight"
     */
    public function testPropertyHarvestedWetWeight()
    {
    }

    /**
     * Test attribute "harvest_count"
     */
    public function testPropertyHarvestCount()
    {
    }

    /**
     * Test attribute "is_on_hold"
     */
    public function testPropertyIsOnHold()
    {
    }

    /**
     * Test attribute "planted_date"
     */
    public function testPropertyPlantedDate()
    {
    }

    /**
     * Test attribute "vegetative_date"
     */
    public function testPropertyVegetativeDate()
    {
    }

    /**
     * Test attribute "flowering_date"
     */
    public function testPropertyFloweringDate()
    {
    }

    /**
     * Test attribute "harvested_date"
     */
    public function testPropertyHarvestedDate()
    {
    }

    /**
     * Test attribute "destroyed_date"
     */
    public function testPropertyDestroyedDate()
    {
    }

    /**
     * Test attribute "destroyed_note"
     */
    public function testPropertyDestroyedNote()
    {
    }

    /**
     * Test attribute "destroyed_by_user_name"
     */
    public function testPropertyDestroyedByUserName()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }
}
