<?php
/**
 * PlantBatchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PlantBatchTest Class Doc Comment
 *
 * @category    Class
 * @description PlantBatch
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlantBatchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PlantBatch"
     */
    public function testPlantBatch()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "room_id"
     */
    public function testPropertyRoomId()
    {
    }

    /**
     * Test attribute "room_name"
     */
    public function testPropertyRoomName()
    {
    }

    /**
     * Test attribute "strain_id"
     */
    public function testPropertyStrainId()
    {
    }

    /**
     * Test attribute "strain_name"
     */
    public function testPropertyStrainName()
    {
    }

    /**
     * Test attribute "patient_license_number"
     */
    public function testPropertyPatientLicenseNumber()
    {
    }

    /**
     * Test attribute "untracked_count"
     */
    public function testPropertyUntrackedCount()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "tracked_count"
     */
    public function testPropertyTrackedCount()
    {
    }

    /**
     * Test attribute "live_count"
     */
    public function testPropertyLiveCount()
    {
    }

    /**
     * Test attribute "packaged_count"
     */
    public function testPropertyPackagedCount()
    {
    }

    /**
     * Test attribute "harvested_count"
     */
    public function testPropertyHarvestedCount()
    {
    }

    /**
     * Test attribute "destroyed_count"
     */
    public function testPropertyDestroyedCount()
    {
    }

    /**
     * Test attribute "source_package_id"
     */
    public function testPropertySourcePackageId()
    {
    }

    /**
     * Test attribute "source_package_label"
     */
    public function testPropertySourcePackageLabel()
    {
    }

    /**
     * Test attribute "source_plant_id"
     */
    public function testPropertySourcePlantId()
    {
    }

    /**
     * Test attribute "source_plant_label"
     */
    public function testPropertySourcePlantLabel()
    {
    }

    /**
     * Test attribute "planted_date"
     */
    public function testPropertyPlantedDate()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }
}
