<?php
/**
 * RemediatePackageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RemediatePackageTest Class Doc Comment
 *
 * @category    Class
 * @description RemediatePackage
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RemediatePackageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RemediatePackage"
     */
    public function testRemediatePackage()
    {
    }

    /**
     * Test attribute "package_label"
     */
    public function testPropertyPackageLabel()
    {
    }

    /**
     * Test attribute "remediation_method_name"
     */
    public function testPropertyRemediationMethodName()
    {
    }

    /**
     * Test attribute "remediation_date"
     */
    public function testPropertyRemediationDate()
    {
    }

    /**
     * Test attribute "remediation_steps"
     */
    public function testPropertyRemediationSteps()
    {
    }
}
