<?php
/**
 * PatientsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * PatientsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PatientsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for patientsV1ActiveGet
     *
     * .
     *
     */
    public function testPatientsV1ActiveGet()
    {
    }

    /**
     * Test case for patientsV1AddPost
     *
     * .
     *
     */
    public function testPatientsV1AddPost()
    {
    }

    /**
     * Test case for patientsV1IdDelete
     *
     * .
     *
     */
    public function testPatientsV1IdDelete()
    {
    }

    /**
     * Test case for patientsV1IdGet
     *
     * .
     *
     */
    public function testPatientsV1IdGet()
    {
    }

    /**
     * Test case for patientsV1StatusPatientLicenseNumberGet
     *
     * .
     *
     */
    public function testPatientsV1StatusPatientLicenseNumberGet()
    {
    }

    /**
     * Test case for patientsV1UpdatePost
     *
     * .
     *
     */
    public function testPatientsV1UpdatePost()
    {
    }
}
