<?php
/**
 * SalesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * SalesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SalesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for salesV1CustomertypesGet
     *
     * .
     *
     */
    public function testSalesV1CustomertypesGet()
    {
    }

    /**
     * Test case for salesV1ReceiptsGet
     *
     * .
     *
     */
    public function testSalesV1ReceiptsGet()
    {
    }

    /**
     * Test case for salesV1ReceiptsIdDelete
     *
     * .
     *
     */
    public function testSalesV1ReceiptsIdDelete()
    {
    }

    /**
     * Test case for salesV1ReceiptsIdGet
     *
     * .
     *
     */
    public function testSalesV1ReceiptsIdGet()
    {
    }

    /**
     * Test case for salesV1ReceiptsPost
     *
     * .
     *
     */
    public function testSalesV1ReceiptsPost()
    {
    }

    /**
     * Test case for salesV1ReceiptsPut
     *
     * .
     *
     */
    public function testSalesV1ReceiptsPut()
    {
    }

    /**
     * Test case for salesV1TransactionsDatePost
     *
     * .
     *
     */
    public function testSalesV1TransactionsDatePost()
    {
    }

    /**
     * Test case for salesV1TransactionsDatePut
     *
     * .
     *
     */
    public function testSalesV1TransactionsDatePut()
    {
    }

    /**
     * Test case for salesV1TransactionsSalesDateStartSalesDateEndGet
     *
     * .
     *
     */
    public function testSalesV1TransactionsSalesDateStartSalesDateEndGet()
    {
    }
}
