<?php
/**
 * StrainsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * StrainsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StrainsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for strainsV1ActiveGet
     *
     * .
     *
     */
    public function testStrainsV1ActiveGet()
    {
    }

    /**
     * Test case for strainsV1CreatePost
     *
     * .
     *
     */
    public function testStrainsV1CreatePost()
    {
    }

    /**
     * Test case for strainsV1IdDelete
     *
     * .
     *
     */
    public function testStrainsV1IdDelete()
    {
    }

    /**
     * Test case for strainsV1IdGet
     *
     * .
     *
     */
    public function testStrainsV1IdGet()
    {
    }

    /**
     * Test case for strainsV1UpdatePost
     *
     * .
     *
     */
    public function testStrainsV1UpdatePost()
    {
    }
}
