<?php
/**
 * AdditivePlantBatchesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AdditivePlantBatchesTest Class Doc Comment
 *
 * @category    Class
 * @description AdditivePlantBatches
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdditivePlantBatchesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdditivePlantBatches"
     */
    public function testAdditivePlantBatches()
    {
    }

    /**
     * Test attribute "additive_type"
     */
    public function testPropertyAdditiveType()
    {
    }

    /**
     * Test attribute "product_trade_name"
     */
    public function testPropertyProductTradeName()
    {
    }

    /**
     * Test attribute "epa_registration_number"
     */
    public function testPropertyEpaRegistrationNumber()
    {
    }

    /**
     * Test attribute "product_supplier"
     */
    public function testPropertyProductSupplier()
    {
    }

    /**
     * Test attribute "application_device"
     */
    public function testPropertyApplicationDevice()
    {
    }

    /**
     * Test attribute "total_amount_applied"
     */
    public function testPropertyTotalAmountApplied()
    {
    }

    /**
     * Test attribute "total_amount_unit_of_measure"
     */
    public function testPropertyTotalAmountUnitOfMeasure()
    {
    }

    /**
     * Test attribute "active_ingredients"
     */
    public function testPropertyActiveIngredients()
    {
    }

    /**
     * Test attribute "plant_batch_name"
     */
    public function testPropertyPlantBatchName()
    {
    }

    /**
     * Test attribute "actual_date"
     */
    public function testPropertyActualDate()
    {
    }
}
