<?php
/**
 * ChangeGrowthPhaseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChangeGrowthPhaseTest Class Doc Comment
 *
 * @category    Class
 * @description ChangeGrowthPhase
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChangeGrowthPhaseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ChangeGrowthPhase"
     */
    public function testChangeGrowthPhase()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "starting_tag"
     */
    public function testPropertyStartingTag()
    {
    }

    /**
     * Test attribute "growth_phase"
     */
    public function testPropertyGrowthPhase()
    {
    }

    /**
     * Test attribute "new_room"
     */
    public function testPropertyNewRoom()
    {
    }

    /**
     * Test attribute "growth_date"
     */
    public function testPropertyGrowthDate()
    {
    }

    /**
     * Test attribute "patient_license_number"
     */
    public function testPropertyPatientLicenseNumber()
    {
    }
}
