<?php
/**
 * CreateItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateItemTest Class Doc Comment
 *
 * @category    Class
 * @description CreateItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateItem"
     */
    public function testCreateItem()
    {
    }

    /**
     * Test attribute "item_category"
     */
    public function testPropertyItemCategory()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "unit_of_measure"
     */
    public function testPropertyUnitOfMeasure()
    {
    }

    /**
     * Test attribute "strain"
     */
    public function testPropertyStrain()
    {
    }

    /**
     * Test attribute "item_brand"
     */
    public function testPropertyItemBrand()
    {
    }

    /**
     * Test attribute "administration_method"
     */
    public function testPropertyAdministrationMethod()
    {
    }

    /**
     * Test attribute "unit_cbd_percent"
     */
    public function testPropertyUnitCbdPercent()
    {
    }

    /**
     * Test attribute "unit_cbd_content"
     */
    public function testPropertyUnitCbdContent()
    {
    }

    /**
     * Test attribute "unit_cbd_content_unit_of_measure"
     */
    public function testPropertyUnitCbdContentUnitOfMeasure()
    {
    }

    /**
     * Test attribute "unit_thc_percent"
     */
    public function testPropertyUnitThcPercent()
    {
    }

    /**
     * Test attribute "unit_thc_content"
     */
    public function testPropertyUnitThcContent()
    {
    }

    /**
     * Test attribute "unit_thc_content_unit_of_measure"
     */
    public function testPropertyUnitThcContentUnitOfMeasure()
    {
    }

    /**
     * Test attribute "unit_volume"
     */
    public function testPropertyUnitVolume()
    {
    }

    /**
     * Test attribute "unit_volume_unit_of_measure"
     */
    public function testPropertyUnitVolumeUnitOfMeasure()
    {
    }

    /**
     * Test attribute "unit_weight"
     */
    public function testPropertyUnitWeight()
    {
    }

    /**
     * Test attribute "unit_weight_unit_of_measure"
     */
    public function testPropertyUnitWeightUnitOfMeasure()
    {
    }

    /**
     * Test attribute "serving_size"
     */
    public function testPropertyServingSize()
    {
    }

    /**
     * Test attribute "supply_duration_days"
     */
    public function testPropertySupplyDurationDays()
    {
    }

    /**
     * Test attribute "ingredients"
     */
    public function testPropertyIngredients()
    {
    }
}
