<?php
/**
 * FacilityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FacilityTest Class Doc Comment
 *
 * @category    Class
 * @description Facility
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FacilityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Facility"
     */
    public function testFacility()
    {
    }

    /**
     * Test attribute "hire_date"
     */
    public function testPropertyHireDate()
    {
    }

    /**
     * Test attribute "is_owner"
     */
    public function testPropertyIsOwner()
    {
    }

    /**
     * Test attribute "is_manager"
     */
    public function testPropertyIsManager()
    {
    }

    /**
     * Test attribute "occupations"
     */
    public function testPropertyOccupations()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "credentialed_date"
     */
    public function testPropertyCredentialedDate()
    {
    }

    /**
     * Test attribute "support_activation_date"
     */
    public function testPropertySupportActivationDate()
    {
    }

    /**
     * Test attribute "support_expiration_date"
     */
    public function testPropertySupportExpirationDate()
    {
    }

    /**
     * Test attribute "support_last_paid_date"
     */
    public function testPropertySupportLastPaidDate()
    {
    }

    /**
     * Test attribute "facility_type"
     */
    public function testPropertyFacilityType()
    {
    }

    /**
     * Test attribute "license"
     */
    public function testPropertyLicense()
    {
    }
}
