<?php
/**
 * HarvestPackageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HarvestPackageTest Class Doc Comment
 *
 * @category    Class
 * @description HarvestPackage
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HarvestPackageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HarvestPackage"
     */
    public function testHarvestPackage()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "room"
     */
    public function testPropertyRoom()
    {
    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {
    }

    /**
     * Test attribute "unit_of_weight"
     */
    public function testPropertyUnitOfWeight()
    {
    }

    /**
     * Test attribute "patient_license_number"
     */
    public function testPropertyPatientLicenseNumber()
    {
    }

    /**
     * Test attribute "is_production_batch"
     */
    public function testPropertyIsProductionBatch()
    {
    }

    /**
     * Test attribute "production_batch_number"
     */
    public function testPropertyProductionBatchNumber()
    {
    }

    /**
     * Test attribute "product_requires_remediation"
     */
    public function testPropertyProductRequiresRemediation()
    {
    }

    /**
     * Test attribute "remediate_product"
     */
    public function testPropertyRemediateProduct()
    {
    }

    /**
     * Test attribute "remediation_method_id"
     */
    public function testPropertyRemediationMethodId()
    {
    }

    /**
     * Test attribute "remediation_date"
     */
    public function testPropertyRemediationDate()
    {
    }

    /**
     * Test attribute "remediation_steps"
     */
    public function testPropertyRemediationSteps()
    {
    }

    /**
     * Test attribute "actual_date"
     */
    public function testPropertyActualDate()
    {
    }

    /**
     * Test attribute "ingredients"
     */
    public function testPropertyIngredients()
    {
    }
}
