<?php
/**
 * HarvestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HarvestTest Class Doc Comment
 *
 * @category    Class
 * @description Harvest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HarvestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Harvest"
     */
    public function testHarvest()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "harvest_type"
     */
    public function testPropertyHarvestType()
    {
    }

    /**
     * Test attribute "source_strain_count"
     */
    public function testPropertySourceStrainCount()
    {
    }

    /**
     * Test attribute "source_strain_names"
     */
    public function testPropertySourceStrainNames()
    {
    }

    /**
     * Test attribute "strains"
     */
    public function testPropertyStrains()
    {
    }

    /**
     * Test attribute "drying_room_id"
     */
    public function testPropertyDryingRoomId()
    {
    }

    /**
     * Test attribute "drying_room_name"
     */
    public function testPropertyDryingRoomName()
    {
    }

    /**
     * Test attribute "patient_license_number"
     */
    public function testPropertyPatientLicenseNumber()
    {
    }

    /**
     * Test attribute "current_weight"
     */
    public function testPropertyCurrentWeight()
    {
    }

    /**
     * Test attribute "total_waste_weight"
     */
    public function testPropertyTotalWasteWeight()
    {
    }

    /**
     * Test attribute "plant_count"
     */
    public function testPropertyPlantCount()
    {
    }

    /**
     * Test attribute "total_wet_weight"
     */
    public function testPropertyTotalWetWeight()
    {
    }

    /**
     * Test attribute "total_restored_weight"
     */
    public function testPropertyTotalRestoredWeight()
    {
    }

    /**
     * Test attribute "package_count"
     */
    public function testPropertyPackageCount()
    {
    }

    /**
     * Test attribute "total_packaged_weight"
     */
    public function testPropertyTotalPackagedWeight()
    {
    }

    /**
     * Test attribute "unit_of_weight_name"
     */
    public function testPropertyUnitOfWeightName()
    {
    }

    /**
     * Test attribute "lab_testing_state"
     */
    public function testPropertyLabTestingState()
    {
    }

    /**
     * Test attribute "lab_testing_state_date"
     */
    public function testPropertyLabTestingStateDate()
    {
    }

    /**
     * Test attribute "is_on_hold"
     */
    public function testPropertyIsOnHold()
    {
    }

    /**
     * Test attribute "harvest_start_date"
     */
    public function testPropertyHarvestStartDate()
    {
    }

    /**
     * Test attribute "finished_date"
     */
    public function testPropertyFinishedDate()
    {
    }

    /**
     * Test attribute "archived_date"
     */
    public function testPropertyArchivedDate()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }
}
