<?php
/**
 * PutSaleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * METRC API
 *
 * Metrc Web API Documentation
 *
 * OpenAPI spec version: 0.2
 * Contact: paul.kohlhoff@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PutSaleTest Class Doc Comment
 *
 * @category    Class
 * @description PutSale
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PutSaleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PutSale"
     */
    public function testPutSale()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "sales_date_time"
     */
    public function testPropertySalesDateTime()
    {
    }

    /**
     * Test attribute "sales_customer_type"
     */
    public function testPropertySalesCustomerType()
    {
    }

    /**
     * Test attribute "patient_license_number"
     */
    public function testPropertyPatientLicenseNumber()
    {
    }

    /**
     * Test attribute "caregiver_license_number"
     */
    public function testPropertyCaregiverLicenseNumber()
    {
    }

    /**
     * Test attribute "identification_method"
     */
    public function testPropertyIdentificationMethod()
    {
    }

    /**
     * Test attribute "transactions"
     */
    public function testPropertyTransactions()
    {
    }
}
